"use client";

/**
 * CleanEat business logic hook
 */

import { useState, useCallback, useEffect } from "react";
import { useWallet } from "./useWallet";
import { useContract } from "./useContract";
import { useFhevm } from "../fhevm/useFhevm";
import { getCleanEatAddress } from "../abi/CleanEatAddresses";

// This will be generated by genabi script
let CleanEatABI: any = null;
try {
  CleanEatABI = require("../abi/CleanEatABI").CleanEatABI;
} catch (e) {
  console.warn("CleanEat ABI not found. Run: npm run genabi");
}

export interface RatingData {
  stallId: number;
  nutritionScore: number;
  satisfactionScore: number;
  comment: string;
}

export interface StallAggregates {
  avgNutrition: number;
  avgSatisfaction: number;
  totalRatings: number;
}

export interface UserRating {
  ratingId: number;
  user: string;
  stallId: number;
  nutritionHandle: bigint;
  satisfactionHandle: bigint;
  comment: string;
  timestamp: number;
  decryptedNutrition?: number;
  decryptedSatisfaction?: number;
}

export function useCleanEat() {
  const { chainId, account } = useWallet();
  const { instance: fhevmInstance, initializeFhevm } = useFhevm();
  
  const contractAddress = chainId ? getCleanEatAddress(chainId) : undefined;
  const contract = useContract(contractAddress, CleanEatABI);

  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Initialize FHEVM when wallet connected
  useEffect(() => {
    if (chainId && contractAddress && account) {
      const provider = (window as any).ethereum;
      if (provider) {
        initializeFhevm(chainId, contractAddress, provider, account);
      }
    }
  }, [chainId, contractAddress, account, initializeFhevm]);

  /**
   * Submit encrypted rating
   */
  const submitRating = useCallback(
    async (data: RatingData): Promise<string | null> => {
      if (!contract || !fhevmInstance || !account) {
        setError("Contract or FHEVM not initialized");
        return null;
      }

      setIsLoading(true);
      setError(null);

      try {
        const contractAddr = await contract.getAddress();
        
        // Create encrypted input for nutrition
        const nutritionInput = fhevmInstance.createEncryptedInput(contractAddr, account);
        nutritionInput.add16(data.nutritionScore);
        const encNutrition = await nutritionInput.encrypt();

        // Create encrypted input for satisfaction
        const satisfactionInput = fhevmInstance.createEncryptedInput(contractAddr, account);
        satisfactionInput.add16(data.satisfactionScore);
        const encSatisfaction = await satisfactionInput.encrypt();

        // Submit transaction with handles and proofs
        const tx = await contract.submitRating(
          data.stallId,
          encNutrition.handles[0],
          encNutrition.inputProof,
          encSatisfaction.handles[0],
          encSatisfaction.inputProof,
          data.comment
        );

        console.log("📝 Rating submitted, waiting for confirmation...");
        const receipt = await tx.wait();
        
        console.log("✅ Rating confirmed:", receipt.hash);
        return receipt.hash;
      } catch (err: any) {
        console.error("Failed to submit rating:", err);
        setError(err.message || "Failed to submit rating");
        return null;
      } finally {
        setIsLoading(false);
      }
    },
    [contract, fhevmInstance, account]
  );

  /**
   * Get stall aggregates (decrypts encrypted sums)
   * Optionally pass pre-obtained signature to avoid re-signing
   */
  const getStallAggregates = useCallback(
    async (stallId: number, ethersSigner?: any, storage?: any, preObtainedSig?: any): Promise<StallAggregates | null> => {
      if (!contract || !fhevmInstance) {
        setError("Contract or FHEVM not initialized");
        return null;
      }

      try {
        const contractAddr = await contract.getAddress();
        
        // Read the encrypted values (view function)
        const result = await contract.getStallAggregates.staticCall(stallId);
        
        // Parse result (tuple with named properties)
        const nutritionSum = result.nutritionSum || result[0];
        const satisfactionSum = result.satisfactionSum || result[1];
        const totalRatings = result.totalRatings || result[2];
        
        const total = Number(totalRatings);
        
        // If no ratings, return zeros (no need to decrypt)
        if (total === 0) {
          return {
            avgNutrition: 0,
            avgSatisfaction: 0,
            totalRatings: 0,
          };
        }

        // Need signature for decrypt (both Mock and Relayer modes use same approach)
        // Note: allowAllStallAggregates() only grants permission for stalls with ratings
        if (!ethersSigner || !storage) {
          return {
            avgNutrition: 0,
            avgSatisfaction: 0,
            totalRatings: total,
          };
        }

        // Use pre-obtained signature or get a new one
        let sig = preObtainedSig;
        if (!sig) {
          const { FhevmDecryptionSignature } = await import("../fhevm/FhevmDecryptionSignature");
          sig = await FhevmDecryptionSignature.loadOrSign(
            fhevmInstance,
            [contractAddr as `0x${string}`],
            ethersSigner,
            storage
          );
        }

        if (!sig) {
          return {
            avgNutrition: 0,
            avgSatisfaction: 0,
            totalRatings: total,
          };
        }

        // Decrypt sums
        const nutritionHandle = String(nutritionSum);
        const satisfactionHandle = String(satisfactionSum);

        const results = await fhevmInstance.userDecrypt(
          [
            { handle: nutritionHandle, contractAddress: contractAddr },
            { handle: satisfactionHandle, contractAddress: contractAddr },
          ],
          sig.privateKey,
          sig.publicKey,
          sig.signature,
          sig.contractAddresses,
          sig.userAddress,
          sig.startTimestamp,
          sig.durationDays
        );

        const nutritionSumDecrypted = Number(results[nutritionHandle]);
        const satisfactionSumDecrypted = Number(results[satisfactionHandle]);

        return {
          avgNutrition: Math.round(nutritionSumDecrypted / total),
          avgSatisfaction: Math.round(satisfactionSumDecrypted / total),
          totalRatings: total,
        };
      } catch (err: any) {
        console.error("Failed to get stall aggregates:", err);
        setError(err.message || "Failed to get aggregates");
        return null;
      }
    },
    [contract, fhevmInstance]
  );

  /**
   * Get all stall aggregates (optimized: single authorization + single signature)
   */
  const getAllStallAggregates = useCallback(async (ethersSigner?: any, storage?: any): Promise<StallAggregates[]> => {
    if (!contract || !fhevmInstance) {
      return [];
    }

    // Step 1: Grant decryption permission for all stalls with ONE transaction
    try {
      console.log("🔐 Granting decryption permission for all stalls...");
      const allowTx = await contract.allowAllStallAggregates();
      await allowTx.wait();
      console.log("✅ Decryption permission granted for all stalls");
    } catch (e) {
      console.error("Failed to grant decryption permission:", e);
      return [];
    }

    // Step 2: Get signature once for all stalls (works for both Mock and Relayer modes)
    let sig = null;
    if (ethersSigner && storage) {
      try {
        const contractAddr = await contract.getAddress();
        const { FhevmDecryptionSignature } = await import("../fhevm/FhevmDecryptionSignature");
        sig = await FhevmDecryptionSignature.loadOrSign(
          fhevmInstance,
          [contractAddr as `0x${string}`],
          ethersSigner,
          storage
        );
        console.log("✅ Got decryption signature (will reuse for all stalls)");
      } catch (e) {
        console.warn("Could not get decryption signature:", e);
      }
    }

    // Step 3: Get all stall aggregates using the same signature
    const results: StallAggregates[] = [];
    for (let i = 0; i < 5; i++) {
      const data = await getStallAggregates(i, ethersSigner, storage, sig);
      if (data) {
        results.push(data);
      }
    }
    return results;
  }, [contract, fhevmInstance, getStallAggregates]);

  /**
   * Get user ratings
   */
  const getUserRatings = useCallback(
    async (userAddress?: string): Promise<UserRating[]> => {
      if (!contract) {
        setError("Contract not initialized");
        return [];
      }

      const address = userAddress || account;
      if (!address) return [];

      try {
        const ratingIds = await contract.getUserRatings(address);
        
        const ratings: UserRating[] = [];
        for (const id of ratingIds) {
          const [user, stallId, nutrition, satisfaction, comment, timestamp] =
            await contract.getRating(id);

          // euint16 is returned as bytes32/string handle
          ratings.push({
            ratingId: Number(id),
            user,
            stallId: Number(stallId),
            nutritionHandle: BigInt(nutrition),
            satisfactionHandle: BigInt(satisfaction),
            comment,
            timestamp: Number(timestamp),
          });
        }

        return ratings;
      } catch (err: any) {
        console.error("Failed to get user ratings:", err);
        setError(err.message || "Failed to get ratings");
        return [];
      }
    },
    [contract, account]
  );

  /**
   * Decrypt rating
   */
  const decryptRating = useCallback(
    async (ratingId: number, ethersSigner: any, storage: any): Promise<{ nutrition: number; satisfaction: number } | null> => {
      if (!contract || !fhevmInstance || !account) {
        setError("Contract or FHEVM not initialized");
        return null;
      }

      try {
        const contractAddr = await contract.getAddress();

        // Get signature for decryption
        const { FhevmDecryptionSignature } = await import("../fhevm/FhevmDecryptionSignature");
        const sig = await FhevmDecryptionSignature.loadOrSign(
          fhevmInstance,
          [contractAddr as `0x${string}`],
          ethersSigner,
          storage
        );

        if (!sig) {
          setError("Failed to get decryption signature");
          return null;
        }

        // Allow decryption (may already be allowed from submitRating)
        try {
          const tx = await contract.allowUserDecrypt(ratingId);
          await tx.wait();
        } catch (e) {
          // May already be allowed, continue
          console.log("Allow may have already been called");
        }

        // Get handles
        const [, , nutrition, satisfaction] = await contract.getRating(ratingId);

        // Convert to string handles
        const nutritionHandle = String(nutrition);
        const satisfactionHandle = String(satisfaction);

        // Decrypt using userDecrypt with full signature
        const results = await fhevmInstance.userDecrypt(
          [
            { handle: nutritionHandle, contractAddress: contractAddr },
            { handle: satisfactionHandle, contractAddress: contractAddr },
          ],
          sig.privateKey,
          sig.publicKey,
          sig.signature,
          sig.contractAddresses,
          sig.userAddress,
          sig.startTimestamp,
          sig.durationDays
        );

        return {
          nutrition: Number(results[nutritionHandle]),
          satisfaction: Number(results[satisfactionHandle]),
        };
      } catch (err: any) {
        console.error("Failed to decrypt rating:", err);
        setError(err.message || "Failed to decrypt");
        return null;
      }
    },
    [contract, fhevmInstance, account]
  );

  /**
   * Check if user is authorized logistics
   */
  const isAuthorized = useCallback(
    async (userAddress?: string): Promise<boolean> => {
      if (!contract) return false;

      const address = userAddress || account;
      if (!address) return false;

      try {
        return await contract.isAuthorized(address);
      } catch (err) {
        console.error("Failed to check authorization:", err);
        return false;
      }
    },
    [contract, account]
  );

  /**
   * Get thresholds
   */
  const getThresholds = useCallback(async (): Promise<{ nutrition: number; satisfaction: number } | null> => {
    if (!contract) return null;

    try {
      const [nutrition, satisfaction] = await contract.getThresholds();
      return {
        nutrition: Number(nutrition),
        satisfaction: Number(satisfaction),
      };
    } catch (err) {
      console.error("Failed to get thresholds:", err);
      return null;
    }
  }, [contract]);

  return {
    contract,
    contractAddress,
    isLoading,
    error,
    submitRating,
    getStallAggregates,
    getAllStallAggregates,
    getUserRatings,
    decryptRating,
    isAuthorized,
    getThresholds,
  };
}

